#base/values/metallb.yaml
pools:
  - name: "default-pool"
    ipRange:
      - "192.168.1.141-192.168.1.200"
  - name: "traefik-pool"
    ipRange:
      - "192.168.1.140/32"
  - name: "haproxy-pool"
    ipRange:
      - "192.168.1.139/32"
