#base/values/metallb.yaml
pools:
  - name: "default-pool"
    ipRange:
      - "192.168.1.141-192.168.1.200"
  - name: "traefik-pool-1"
    ipRange:
      - "192.168.1.140/32"
      - "192.168.1.241/32"
