---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCRnBrzvg7SEuiCxGUdhwiDb4e2ovS1/nJKG5MYwBQ6GDp2RdxP++Gu2oaWyrrBbd31nQFh8UWie5UPFthczjlMIlMZXjsKDqMKb1r7qc6xAMw9y/61gyPY0SsM/p5cFWxES0QMmeBbt6x5jWHVw1pwbR316SDxcZX7IUv34BLCCRqqnE0NFf358x4viWsjLqFX2G+838o6a7jCKf2SZHFhGGo4DOLpp794rEo7n7uxgUso/NM96+g3962H/GmrhLpw3uesTft+knoSGeGWeE3Xbb99qBN4I0D1cxeiho3okV5gKiRSniP2FknILLW482hjKfJCm7IyvqLd2MeLn+VW4gzPdbrsUbUNsNoBuB8rOC2SedfyHZODmAn4SbWaALy5ads4NDxnF1E/TtBetWIun8KHBv3UNya01G+Rf2SnvnDJiXG6DG5FmSSzHxPpAQRMNUniNVNO0xjtTbnxPMKqrgZxoVIedKPzenWVdaxYR841RNT/MbC7amI8VXyVSm/AvxSznHryxWz0xyPUvmQ0o0qRuOhMhXsdUQbAOIEqFMOXH6oD4aYWlXki2wGME+9b0JLp2VKiJtj6jBAEJkLpbil4hvmQdKvdwe3C3yZ+Hw3XhqVHIebGt3Thym5wavRwDKnQ+BgzR0ryCy04wxd93ILUY0fD/fmm9sUzKOCBZFSpFXqPfgQJPo78OcCpcQdY26SaCDL0XgW5UXPEKol/U5QijBFMmeXcAXcA+eC3UUW3+jb8jVno
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
