bases:
  - ../defaults.yaml
  - ../repositories.yaml

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 75.6.0
    timeout: 600
    values:
      - ./values/kube-prometheus-stack.yaml
