---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alchemy-token
  namespace: eth
spec:
  encryptedData:
    ALCHEMY_TOKEN: AgBbxU1FfgyvUx7c/mekHvyb0H81wVJQcucupfkmXMxPa80Vv58WG/sbzuLHjGKeTfwnkXHCTuz49/QtpgJbSm9aEUcHepJi/9a5jjG8oYESQQHdZZU/vUwXhfqynculWLA6cg7Nz0CEOr7DZGx54wgegVr6bc1RTCFNOdQq+GV9oUCI9RKK1yWXdUDbMC65LYhTBypyDm04NaCbjTk1pEn3FLt0+F+W0GKOu21LFm0d+MBZt2kvkR/eCb9qYecu1vpqTCfJbNaHxY52uVCvVjn4mYAvv5zys45AViy+KrRlDl/LOyZzoeHW3fxHBVmthlvrhsX17UJdjkjlMwUKx0gmJdMVdY5VBdaBpXh6T5rwz5ekkxKFWhEyNCyN/HNoGqMNiXR58IEOD2KE1NNNsRKWrgHqNBKweUqPIcghGh25cNqghoglxalYDJb7mOTSC0wu1Lw1LQUd+2qGTF6C/2Y7BBVINKR6jAx0tixO5L9LqqkyYq0wP37sB3ns4j6lZEhYdyHCOxbt0QbhQPaO2D6acIuw15P1JVNpImClNDZHO+oBnxaFwIVCSSi1hnVdSLkiAFO70uKDKfilU6R8nmfNnE8cZB7VF0TTjQgd+005Etx1sN7Wr9frEP51Zw9gzZS3k5DOzCA2535eET6+Qu8mErro9J75xhBsj1sKEugplEREus+31orlmjgINyYsUoDAmEJ8wu/DXsW2TpaxjfSImZiaELKBkrE3r3YNmTv8Aw==
  template:
    metadata:
      name: alchemy-token
      namespace: eth
