apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "this.name" . }}
  namespace: eth
spec:
  dnsNames:
    - dshackle-test.traefik.bobaklabs.com
  secretName: {{ include "this.name" . }}-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
