apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "this.name" . | quote }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
data:
  dshackle.yaml: |
    version: v1
    port: 2449
    tls:
      enabled: false

    proxy:
      host: 0.0.0.0
      port: 8545
      websocket: true
      tls:
        enabled: false
      routes:
        - id: sepolia
          blockchain: sepolia
          chain: sepolia
        - id: ethereum
          blockchain: ethereum
          chain: ethereum

    cluster:
      upstreams:
        - id: sepolia-nodes-1
          options:
            disable-validation: true
          chain: sepolia
          connection:
            generic:
              rpc:
                url: "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_TOKEN}"
              ws:
                url: "wss://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_TOKEN}"
        - id: eth-nodes-1
          options:
            disable-validation: true
          chain: ethereum
          connection:
            generic:
              rpc:
                url: "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_TOKEN}"
              ws:
                url: "wss://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_TOKEN}"

    cache:
      redis:
        enabled: true
        host: 127.0.0.1
        port: 6379
        db: 0
        password: ${REDIS_PASSWORD}
