apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "this.name" . | quote }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "this.name" . | quote }}
  selector:
    matchLabels:
      {{- include "this.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "this.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "this.name" . | quote }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: false
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: dshackle
          image: "drpcorg/dshackle:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redisSecretName | quote }}
                  key: REDIS_PASSWORD
            - name: ALCHEMY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "alchemy-token"
                  key: ALCHEMY_TOKEN
          volumeMounts:
            - name: config-volume
              mountPath: /etc/dshackle
              readOnly: true
          args:
            - "--config"
            - "/etc/dshackle/dshackle.yaml"
          ports:
            - name: dshackle-http
              containerPort: 8545
        - name: redis
          image: redis:latest
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: MASTER
              value: "true"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redisSecretName | quote }}
                  key: REDIS_PASSWORD
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "this.name" . | quote }}
