apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: http-echo
  namespace: default
spec:
  dnsNames:
    - echo.traefik.bobaklabs.com
  secretName: http-echo-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
