bases:
  - ../defaults.yaml
  - ../repositories.yaml

releases:
  ### IMPORTANT: ###
  ### Create namespace metallb-system manually and after that, run:
  ### kubectl label namespace metallb-system "pod-security.kubernetes.io/enforce=privileged" "pod-security.kubernetes.io/enforce-version=latest" --overwrite
  - name: namespaces
    namespace: default
    chart: ./namespaces

  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.14.9
    values:
      - ./values/metallb.yaml

  - name: metallb-config
    namespace: metallb-system
    chart: ../charts/metallb
    values:
      - ./values/metallb-config.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.17.1
    values:
      - installCRDs: true
      - enableCertificateOwnerRef: true

  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.9.0
    values:
      - ./values/longhorn.yaml

  - name: traefik-v3
    namespace: traefik
    chart: traefik/traefik
    version: 36.3.0
    set:
      - name: service.spec.loadBalancerIP
        value: "192.168.1.140"
      - name: service.spec.annotations.metallb\.io/address-pool
        value: "traefik-pool-1"
    values:
      - ./values/traefik.yaml
  
  - name: certificates
    namespace: default
    chart: ../charts/certificates
    values:
      - ./values/certificates.yaml

  - name: sealed-secrets
    namespace: kube-system
    chart: sealed-secrets/sealed-secrets
    version: 2.17.2
    set:
      - name: fullnameOverride
        value: sealed-secrets-controller

  - name: secrets
    namespace: default
    chart: ./secrets
