# helmfile.yaml
bases:
  - ../defaults.yaml
  - ../repositories.yaml

releases:
  ### IMPORTANT: ###
  ### Create namespace metallb-system manually and after that, run:
  ### kubectl label namespace metallb-system "pod-security.kubernetes.io/enforce=privileged" "pod-security.kubernetes.io/enforce-version=latest" --overwrite
  - name: metallb
    namespace: metallb-system
    createNamespace: false
    chart: metallb/metallb
    version: 0.14.9
    values:
      - ./values/metallb.yaml

  - name: metallb-config
    namespace: metallb-system
    createNamespace: false
    chart: ../charts/metallb
    values:
      - ./values/metallb-config.yaml

  - name: test-app
    namespace: default
    chart: ../charts/test-app
    values:
      - image:
          tag: "1.25.3"
        service:
          type: LoadBalancer
          port: 80

