apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "this.name" . }}
  namespace: monitoring
spec:
  secretName: {{ include "this.name" . }}
  dnsNames:
    - grafana.k8s.bobaklabs.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
