apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "this.name" . }}
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.k8s.bobaklabs.com`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          kind: Service
          port: 80
  tls:
    secretName: grafana-ingress
