#charts/metallb/templates/ipaddresspool.yaml
{{- range .Values.pools }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .name }}
  namespace: metallb-system
spec:
  ipAddressPools:
    - {{ .name }}
{{- end }}
